### ISSUE TITLE
[BUG] Unwrapped inline code when setting "Wrap long lines in code blocks" to "No"

### ISSUE THREAD

**Issue by Leilei332** [TiddlyWiki/TiddlyWiki5#8549] opened 2024-08-23 14:15 UTC
### Describe the bug

When setting "Wrap long lines in code blocks" to "No", the inline code is also unwrapped, which may overflow when the inline code is long.

![图片](https://github.com/user-attachments/assets/d484490d-a679-4159-8393-171fc449b14f)

Test code:

```
`testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest`
```

### Expected behavior

The inline code should be wrapped regardless of the "Wrap long lines in code blocks" setting since it isn't a code block.

### TiddlyWiki Configuration

5.3.6-prerelease

**Comment by pmario** [comment] 2024-08-23 19:06
This is a duplicate of: https://github.com/TiddlyWiki/TiddlyWiki5/issues/8278

That should be fixed with your own PR:  Fix unwrapped oveflowed code blocks not showing scroll bars when setting "Wrap long lines in code blocks" to "No" in "Theme tweaks" #8413

**Closed** 2024-08-24 02:17 UTC
